#!/usr/bin/perl

use strict;
use File::Map qw(map_file);
use JSON::PP;
use Data::Dumper;

my $datafile='wfdrops.json';
my $searchstring = shift(@ARGV);

# map the data file...
map_file( my $datain, $datafile, '<' );
my $data = {};
$data = decode_json( $datain );

foreach my $planet ( keys(%{$data->{missionRewards}}) ) {
    print( "planet: $planet\n" );
    foreach my $location ( keys(%{$data->{missionRewards}->{$planet}}) ) {
        print( "  location: $location ",
               "($data->{missionRewards}->{$planet}->{$location}->{gameMode})\n" );
        dumpLoot($data->{missionRewards}->{$planet}->{$location}->{rewards});
    }
}

# dumpLoot: receive a "rewards", figure out if it's hash or array, dump it
sub dumpLoot {
    my $rewards = shift(@_);
    my $table;
    if ( ref( $rewards ) eq "HASH" ) {
        # a hash containing {A|B|C}, probably
        foreach my $table (sort(keys(%{$rewards}))) {
            print( "   rotation: $table\n" );
            dumpRewardsTable($rewards->{$table});
        }
    } else {
        # an array of hashes
        dumpRewardsTable($rewards);
    }

}
#         if ( $item->{itemName} =~ /.*$searchstring.*/i ) {

sub dumpRewardsTable {
    # stupid tables can be an empty array instead of an array of hashes
    my $list = shift(@_);
    while ( my $item = shift(@{$list}) ) {
        print( "      $item->{itemName} : $item->{chance} \n" );
    }
}
exit;
